<?php
namespace AppBundle\Repository;

/**
 * User_avatarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_avatarRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAvatarById($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT user_avatar.id 
                   FROM AppBundle:User_profile user_profile, AppBundle:Users users, AppBundle:User_avatar user_avatar
                   WHERE users.id=user_profile.users 
                   AND user_avatar.id=user_profile.user_avatar
                   AND users.id=:id')
            ->setParameter('id', $id)
            ->getResult();
    }
}
