<?php
namespace AppBundle\Repository;

/**
 * User_profileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_profileRepository extends \Doctrine\ORM\EntityRepository
{

    //id User
    public function findProfById($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT user_profile.id 
                   FROM AppBundle:User_profile user_profile, AppBundle:Users users 
                   WHERE users.id=user_profile.users 
                   AND users.id=:id')
            ->setParameter('id', $id)
            ->getResult();
    }
}
